### ISSUE TITLE
Missing function scope in vimscript

### ISSUE THREAD

**Issue by Shatur** [hrsh7th/vim-compete#11]
Compete suggest function with it scope but inserts only function name.
I used it with `vim-lamp`

**Steps to reproduce:**

1. Write the following function:

```vim
function! s:test()
endfunction
```

2. Start typing to get completion:

```vim
call s:te
```

**Actual behavior:**

Compete suggests `s:test`, but inserts only `test()` (without scope suffix)

**Expected behavior:**

Compete suggests `s:test`, and inserts `s:test()`.

**Video that represents the issue more clear:**

[![asciicast](https://asciinema.org/a/HvYqaQ6GrOCrKLawWdtYunmWS.svg)](https://asciinema.org/a/HvYqaQ6GrOCrKLawWdtYunmWS)

**Comment by hrsh7th** [comment]
Fixed in `vim-lamp` side.
Could you test with latest vim-lamp?

**Comment by Shatur** [comment]
Thank you, works as expected now.
