### ISSUE TITLE
Completeopt is ignored

### ISSUE THREAD

**Issue by Shatur** [hrsh7th/vim-compete#13]
It looks like `completeopt` is not respected by `compete`. For example, I have `noinsert` specified, but I always have words inserted on matching.
Is it expected? I also tested without any other plugins installed (except vim-compete and vim-vsnip).

Here is the video:

[![asciicast](https://asciinema.org/a/rGD1IiKQlH4YIkxeoGGNdj5Pg.svg)](https://asciinema.org/a/rGD1IiKQlH4YIkxeoGGNdj5Pg)

**Comment by hrsh7th** [comment]
I've added it (https://github.com/hrsh7th/vim-compete/commit/68d92d2c69c910148139dea58c406d123cd92ebd).

But I can't get the expected results via `noinsert`...

**Comment by Shatur** [comment]
Tried, have no difference :(

> But I can't get the expected results via noinsert...

Do you mean that you have items inserted even with `noinsert`?

**Comment by hrsh7th** [comment]
In my environment, `noinsert` does nothing.

I don't know the `noinsert` means.
Sorry, Could you explain noinsert behavior and working example without compete?

**Comment by Shatur** [comment]
`noinsert` option means do not insert selected completion option instantly.
So, when I type `color` and navigate to `colorscheme` in the completion menu I nothing will be inserted until I confirm selected item. Without this option the item will be inserted when I just select it in completion menu.

You can read about it in `:h completeopt`.

Previously it worked with compete. But after a few days - it  does not work.

**Comment by hrsh7th** [comment]
Sorry, It's very helpful that providing working minimal example because noinsert seems to do nothing in my encironment...

**Comment by Shatur** [comment]
Maybe I'm wrong and the issue not in `noinsert`...
In the video from [this](https://github.com/hrsh7th/vim-compete/issues/11) issue:
[![asciicast](https://asciinema.org/a/HvYqaQ6GrOCrKLawWdtYunmWS.svg)](https://asciinema.org/a/HvYqaQ6GrOCrKLawWdtYunmWS)
you can see if I navigate to completion item - nothing inserted. The text inserted only after completion confirmation.

But now item inserted automatically only when I select it.

**Comment by Shatur** [comment]
I'm very sorry! The issue was in my mappings. I accidentally loaded them when testing without configuration.

**Comment by Shatur95** [comment]
> I've added it (68d92d2).

I suggest to undo this commit because user can set default `completeopt`. Sorry for inconvenience.
