### ISSUE TITLE
Press Enter or type command to continue

### ISSUE THREAD

**Issue by Shatur** [hrsh7th/vim-compete#3]
After dfc709d44a0ca9c7bf2e48c125b9cc71e5fecab4 I see the following message before exit:
![image](https://user-images.githubusercontent.com/22453358/78453718-2a9b0680-769c-11ea-82cf-9d65e45ff615.png)
Is this a bug?

**Comment by hrsh7th** [comment]
Thank you for reporting. It's my bad.

Fixed in https://github.com/hrsh7th/vim-compete/commit/f9752dc42a493319dfce5c96297fa5d1157ef626
