### ISSUE TITLE
Close completion window on applying completion

### ISSUE THREAD

**Issue by Shatur** [hrsh7th/vim-compete#4]
Is it possible to close completion window automatically on applying completion?
For example, I used the following for asyncomplete:

```vim
imap <expr> <CR> pumvisible() ? asyncomplete#close_popup() : '<CR>'
```

Is it possible to configure compete in this way? As for me, if I apply completion I never want to see other completion items.

**Comment by hrsh7th** [comment]
Sorry, Probably I didn't understand your mean.
Isn't `<C-y>` enough?

**Comment by Shatur** [comment]
I have the following after `<C-y>`
![изображение](https://user-images.githubusercontent.com/22453358/78531609-6e058a00-77ee-11ea-8223-df4b4761a200.png)

Is it possible to do not show completion after `<C-y>`?

**Comment by Shatur** [comment]
I recodred a video that describes it a bit more. I pressed `<C-y>` several times to accept completion, but completion window still exists. I would like to have it closed after accepted completion.
[![asciicast](https://asciinema.org/a/WJdJxx2oWgzO62DHE7ML45LUI.svg)](https://asciinema.org/a/WJdJxx2oWgzO62DHE7ML45LUI)

**Comment by hrsh7th** [comment]
OK, I will implement `compete#close()`.

But I don't know if the feature is useful.

**Comment by Shatur** [comment]
It would be cool!
As for me I never need opened completion window after `<C-y>`. This is the default behavior in most IDE's. Also with completion window opened I can't press `<CR>` to insert a newline :(

**Comment by hrsh7th** [comment]
My mapping is following.

```viml
inoremap <expr><CR> complete_info(['selected']).selected != -1 ? "\<C-y>" : lexima#expand('<LT>CR>', 'i')
```

I think `pumvisible` is not enough to use for mapping condition. we should use  `complete_info(['selected']).selected != -1` instead.

**Comment by Shatur** [comment]
Thanks for the tip, I will use it too for case when I want to skip completion!
But it would be nice to have the ablility to automatically close completion window after acception too. So it would be very useful to have something like `compete#close()` as in asyncomplete.

**Comment by hrsh7th** [comment]
Supported in
https://github.com/hrsh7th/vim-compete/commit/bb235adf1ff437bb57209fcd56097c277118b33f

**Comment by Shatur** [comment]
Thank you a lot!

**Comment by Shatur** [comment]
I found that it works in 8ad3798ea02381295f9cc5b3d32fb0e1e6498e9d, but stop working in 1594bc5dc6b01b7f30091d392a7ef913091b2488 (latest commit).

**Comment by hrsh7th** [comment]
Thank you.
Probably, the problem was fixed by latest commit.

**Comment by Shatur** [comment]
Yes, thanks!

**Comment by Shatur** [comment]
```vim
imap <expr> <CR> pumvisible() ? compete#close() : '<CR>'
```

Is broken after c053873a83389e75e0e1e9f2f4f27cf2446406ac

**Comment by hrsh7th** [comment]
hm... Sorry for take your time.

I will fix it.

**Comment by Shatur** [comment]
It's okay, normal active developing process. Thank you for the fast response!

**Comment by hrsh7th** [comment]
Fixed in https://github.com/hrsh7th/vim-compete/commit/31ca4f0cdec007f33e191360a63cef75f30181f7

**Comment by Shatur** [comment]
I tested the following:
```vim
imap <expr><CR>  complete_info(['selected']).selected != -1 ? compete#close({ 'confirm': v:true })  : "\<CR>"
imap <expr><Esc> complete_info(['selected']).selected != -1 ? compete#close({ 'confirm': v:false }) : "\<Esc>"
```
`<Esc>` works as expected. But `<CR>` confirms selection without closing completion window (but works on second confirmation).

**Comment by hrsh7th** [comment]
Hm... My environment seems worked...

![ezgif-2-3b6158521177](https://user-images.githubusercontent.com/629908/79059421-cd630e80-7cb4-11ea-9f54-81a10f144876.gif)

**Comment by Shatur** [comment]
I'm sorry, the issue was in my plugin [pear-tree](https://github.com/tmsvg/pear-tree). I solved it by the following:

```vim
imap <expr><CR>  complete_info(['selected']).selected != -1 ? compete#close({ 'confirm': v:true })  : '<Plug>(PearTreeExpand)'
```

Thank you!

**Comment by hrsh7th** [comment]
Oh, I see.

I will update the docs for pear-tree and lexima.vim.
Thanks.

**Comment by Shatur** [comment]
> I will update the docs for pear-tree and lexima.vim.

Good idea!

**Comment by Shatur** [comment]
> ![ezgif-2-3b6158521177](https://user-images.githubusercontent.com/629908/79059421-cd630e80-7cb4-11ea-9f54-81a10f144876.gif)

I see that you have a newline inserted after pressing `<CR>` if no items selected. How do you achieve it?

**Comment by hrsh7th** [comment]
I use complete_info(['selected']) inatead of pumvisible.

**Comment by Shatur** [comment]
I tried it too, but it not works for me... Just now tested without any plugins installed (except `compete`) and with the following minimal configuration:

```vim
imap <expr><CR>  complete_info(['selected']).selected != -1 ? compete#close({ 'confirm': v:true })  : "\<CR>"
imap <expr><Esc> complete_info(['selected']).selected != -1 ? compete#close({ 'confirm': v:false }) : "\<Esc>"

set completeopt=menuone,noselect,noinsert
```

Am I doing something wrong?

**Comment by hrsh7th** [comment]
Ah, Sorry. Please change `imap` to `inoremap` instead.

Hm... But `inoremap` can't expand '<Plug>(PearTreeExpand)' maybe.

I will consider it.

**Comment by Shatur** [comment]
> Ah, Sorry. Please change `imap` to `inoremap` instead.

I tried it with the previous setup and it not helped.

**Comment by hrsh7th** [comment]
Hm...
I will try it with minimal vimrc.

**Comment by Shatur** [comment]
Additional information: `<Esc>` not affected by the same issue: if no item selected it switches to normal mode.
But `<CR>` only closes completion window without inserting a new line if no items selected.

**Comment by hrsh7th** [comment]
I think the problem occur by pear-tree.
Could you test without pear-tree?

**Comment by Shatur** [comment]
My previous tests was without any other plugins  :(

**Comment by hrsh7th** [comment]
Could you try with latest master?

I was check with following vimrc.

```viml
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

let dein = {}
let dein.dir = {}
let dein.dir.install = $XDG_CONFIG_HOME . '/dein.mini/repos/github.com/Shougo/dein.vim'
let dein.dir.plugins = $XDG_CONFIG_HOME . '/dein.mini'

if !isdirectory(dein.dir.install)
  call mkdir(dein.dir.install, 'p')
  call system(printf('git clone https://github.com/Shougo/dein.vim %s', shellescape(dein.dir.install)))
endif

let &runtimepath = &runtimepath . ',' . dein.dir.install
if dein#load_state(dein.dir.install)
  call dein#begin(dein.dir.plugins)
  call dein#add('hrsh7th/vim-compete')
  call dein#local('~/Develop/LocalVimPlugins')
  call dein#end()
endif

if dein#check_install()
  call dein#install()
endif

filetype plugin indent on
syntax enable

augroup vimrc
  autocmd!
augroup END

imap <expr><CR>  complete_info(['selected']).selected != -1 ? compete#close({ 'confirm': v:true })  : "\<CR>"
imap <expr><Esc> complete_info(['selected']).selected != -1 ? compete#close({ 'confirm': v:false }) : "\<Esc>"
```

**Comment by Shatur** [comment]
Thank you, works as expected now!
