### ISSUE TITLE
The ability to specify minumum number of characters for completion

### ISSUE THREAD

**Issue by Shatur** [hrsh7th/vim-compete#5]
I suggest to add the ability to specify minimum word length for completion. This is by default equal to 3 in most IDE's. For example, when I start typing `QS` (for `QString`) in Qt Creator - I will see no completion. But if I continue typing, I sill see completion items after `QSt`. If I remove letter to have `QS` - completion window will still exists. Also rule of 3 characters is ignored for specified trigger characters(`.` and `->` in C++, for example). This will improve performance because usually do not needed to have a lot of completion items after first and second letter. There is a PR for [asyncomplete](https://github.com/prabirshrestha/asyncomplete.vim/pull/135).

**Comment by hrsh7th** [comment]
Supported in https://github.com/hrsh7th/vim-compete/commit/63be73fda080167c831efd341c6a49995f4a05eb

**Comment by Shatur** [comment]
Thank you a lot!

**Comment by Shatur95** [comment]
I tested with the following mapping:
```vim
imap <expr> <CR> pumvisible() ? compete#close() : '<CR>'
```
But it not works for me. Am I do it wrong?
[![asciicast](https://asciinema.org/a/8XNm2GsySaYPS1pD9MFgdMLbj.svg)](https://asciinema.org/a/8XNm2GsySaYPS1pD9MFgdMLbj)

**Comment by Shatur95** [comment]
I found that it stop working in 1594bc5dc6b01b7f30091d392a7ef913091b2488 (latest commit).

**Comment by Shatur** [comment]
I tested it on the latest master with `let g:compete_min_length = 3`, but completion still happens after first character.

**Comment by hrsh7th** [comment]
Sorry, the problem can't reproduce on my machine...

![Kapture 2020-04-07 at 13 45 23](https://user-images.githubusercontent.com/629908/78631069-44279280-78d6-11ea-9305-93188c00f767.gif)

**Comment by Shatur** [comment]
You are right, it works if I specify parameter from the command mode. It not woks if I specify `let g:compete_min_length = 3` in configuration. Is it expected?

**Comment by hrsh7th** [comment]
Sorry it was my rough work. fixed!

**Comment by Shatur** [comment]
Thanks!

**Comment by Shatur** [comment]
I noticed that completion disappear if I remove characters to `compete_min_length`. For example, if I have `preview` word and will truncate it to `pr` the completion window will be closed if I set `compete_min_length`. Is it possible to not close completion window I it was already opened? This is how it works in other editors.

**Comment by hrsh7th** [comment]
Thank you for reporting.

I confirmed the problem.
However the completion trigger condition is a bit complicated so take a time to fix it maybe.

**Comment by hrsh7th** [comment]
Fixed in https://github.com/hrsh7th/vim-compete/commit/a2fba5aeda18c10cb54bd9e6c0b8ed35a00bba06

**Comment by hrsh7th** [comment]
Thank you for reporting.

After many corrections, the behavior has improved considerably.

**Comment by Shatur** [comment]
Thank you, it worked!

I also noticed that completion window blinks for a moment when I deleting chacaters. And statusline (I use Airline) shows INSERT in this moment, than it backs to INSERT COMP. But other completion plugins have the same behavior, so I think that this is not an issue.

**Comment by hrsh7th** [comment]
Thank you~~~

I've fixed flicker when press backspace.

**Comment by Shatur** [comment]
Wow, cool, thank you!

**Comment by Shatur** [comment]
I noticed another small issue with this feature. `vim-vsnim` do not respect this parameter and still suggest my custom snippets after first character. Is this related to compete or it is a `vim-vsnip` issue?

**Comment by hrsh7th** [comment]
Hm... I can't reproduce it.

The below example using `g:compete_min_length = 3`.

![Kapture 2020-04-15 at 0 06 42](https://user-images.githubusercontent.com/629908/79240644-036ae300-7ead-11ea-95a6-45b28a0a0545.gif)

P.S.
Your suggestion and reporting is very helpful for me.
Thanks to improve vim-compete.

**Comment by Shatur** [comment]
Sorry for bothering, I updated to the latest master and everything works now.

> Your suggestion and reporting is very helpful for me.
Thanks to improve vim-compete.

Thank you for working on your plugins!
