### ISSUE TITLE
Add the ability to trigger completion manually

### ISSUE THREAD

**Issue by Shatur** [hrsh7th/vim-compete#7]
Could you add the ability to force trigger completion as in [asyncomplete](https://github.com/prabirshrestha/asyncomplete.vim#force-refresh-completion) or MUcomplete? It also exists in most IDE.

**Comment by hrsh7th** [comment]
It's easy to implement maybe.

I will implement it.

**Comment by hrsh7th** [comment]
Supported.

**Comment by Shatur** [comment]
Thanks!
