### ISSUE TITLE
Cursor flickering on autocompletion

### ISSUE THREAD

**Issue by Shatur** [hrsh7th/vim-compete#8]
By default, the cursor becomes hidden if I press the buttons on the keyboard. But when using compete, the cursor flickers. I recorded a gif do describe the problem a bit more:
![output](https://user-images.githubusercontent.com/22453358/78693129-7e5b5900-7903-11ea-81ca-cfa643026df4.gif)
How it works with other completion plugins:
![output2](https://user-images.githubusercontent.com/22453358/78693298-bc587d00-7903-11ea-82ed-78cd01b69f47.gif)
Is this a bug?

**Comment by hrsh7th** [comment]
It's a strange bug!

Could you tell me the completeopt and shortmess setting?

**Comment by Shatur** [comment]
Of course!
```vim
:set shortmess?
shortmess=filnxtToOFcI

:set completeopt?
completeopt=menu,preview,menuone,noselect,noinsert
```

**Comment by hrsh7th** [comment]
Please test with `set conpleteopt=menuone,noinsert,noselect`

Typical complete engine does modify 'completeopt' automatically but the compete doesn't it.

**Comment by Shatur** [comment]
Tested, but it not fixed the issue :(

**Comment by hrsh7th** [comment]
Hm... Please set `g:compete_throttle_time = 0`

**Comment by Shatur** [comment]
No, still have the issue...

**Comment by hrsh7th** [comment]
Hm... It seems a difficult problem...

I've changed the completion approach as a test.
Could you test with latest master?

**Comment by Shatur** [comment]
Tested, but the problem still exists.

**Comment by Shatur** [comment]
I tested it without vim-lamp and the problem disappear. So, looks the problem is in another plugin.

**Comment by hrsh7th** [comment]
! Thanks.

Hm... I will install neovim-qt...!

**Comment by Shatur** [comment]
Thanks for looking into it!

**Comment by hrsh7th** [comment]
Fixed maybe in vim-lamp.

**Comment by Shatur** [comment]
It fixed the issue, thank you!
