### ISSUE TITLE
Add completeopt source

### ISSUE THREAD

**Issue by Shatur** [hrsh7th/vim-compete#9]
Hello! Is it possible to add `completeopt` as source? I would like to temporary try [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim) or [vim-lsp](https://github.com/prabirshrestha/vim-lsp) instead of vim-lamp for semantic highlighting. If I understand correctly, this LSP plugins can be added via `completeopt`.

**Comment by hrsh7th** [comment]
I think it should not be better to use omnifunc to integrate `LanguageClient-neovim`.

Instead, it should be implemented by compete source is better.

**Comment by hrsh7th** [comment]
Hm... LanguageClient-neovim does not provide `trigger characters` for Vim script...

**Comment by hrsh7th** [comment]
You can use https://github.com/hrsh7th/vim-compete-lcn

**Comment by Shatur** [comment]
Thank you!
Is it possible to add vim-lsp too?
Omnifunc can be useful too for some plugins, for example Tim Pop's [vim-rhubarb](https://github.com/tpope/vim-rhubarb) provides completion via omnifunc.
Will you plan to add omnifunc in future?

**Comment by hrsh7th** [comment]
https://github.com/hrsh7th/vim-compete-omnifunc

I've implemented.
And I'm sorry. I was introduced breaking change at `vim-compete-lamp` and `vim-compete-lcn`.

You should register source manually now.

```viml
call compete#source#lamp#register()
" or
call compete#source#lcn#register()
" or
call compete#source#omnifunc#register()
```

**Comment by hrsh7th** [comment]
NOTE:

omnifunc is not asynchronous so sometimes you get lag if completion is too heavy.

**Comment by Shatur** [comment]
Thank you a lot!

**Comment by Shatur** [comment]
I tested with vim-lamp and omnifunc (you was right, it slow), works as expected.

But `vim-compete-lcn` not works for me. I tried the following:

```vim
let g:LanguageClient_serverCommands = {
  \ 'vim': ['vim-language-server', '--stdio'],
  \ }
call compete#source#lcn#register()
```

LSP can show warnings but completion does not work.

> You should register source manually now.

I think this is very good feature, very convenient for testing.

Is it possible to add in the same way [vim-lsp](https://github.com/prabirshrestha/vim-lsp) (not via omnifunc)?

**Comment by hrsh7th** [comment]
Unfortunately, I met the problem too... It sometimes works, sometimes doesn't.

Creating a vim-lsp source is easy. Please wait.

**Comment by hrsh7th** [comment]
You can use https://github.com/hrsh7th/vim-compete-lsp.

**Comment by Shatur** [comment]
Thank you a lot!
Tested, works as expected. I still like your vim-lamp more (because of speed), but sometimes I need to compare it with other clients without switching from compete. Currently compete is the fastest completion plugin in pure Vimscript.

**Comment by hrsh7th** [comment]
Thank you to compare some other clients with vim-lamp.
If you have some improve point, please tell me it.
